### ISSUE TITLE
[Duplication issue] Spellbinding cloth with some items

### ISSUE THREAD

**Issue by JasonMcRay** [Thaumic-Tinkerer/ThaumicTinkerer#585]
When you try to "wipe" the enchant from Etheric Sword (Extra Utilities), it will give you back the enchanted sword (with durabiílity lowered by 1) and second Etheric Sword without enchants. Also I am not sure if its intended but the Spellbinding Cloth is not consumed upon use. Only its durability lowered (can be used 35x)

Also with trying to remove the innate enchant from GregTech tools (for example Flint Sword, which has Fire Aspect I by default) you effectively dupe the tool still with the enchants on it.

TT: 2.5-1.7.10-161
Thaumcraft: 4.2.1.4
ExU: 1.2.0
GT: 5.06.06

**Comment by JasonMcRay** [comment]
Just updated to TT build 439 and the dupe issue with Etheric Sword seems to be fixed. But GregTech tools still are broken.

When i use the Spellbinding Cloth with Flint Sword, which has Fire Aspect enchant on it - it is its native enchant, I will get exact copy of the Flint Sword. The sword in the crafting grid will remain and it will only take a durability damage.

GT Tools arent using Meta Data to determine its Durability, so I guess thats the issue in here. It uses pure NBT tag to set the durability.

@nekosune sorry to ping you but would like to hear from you if its possible to fix on TT side, or does Greg needs to do something about that. Thank you

**Comment by JasonMcRay** [comment]
Would like to bump this because its still not fixed, and it IS a gamebreaking bug allowing to make infinite number of gregtech tools.

**Comment by nekosune** [comment]
At this, I can not support anything to do with gregtech, as TT's forge version is a different one to the one he asks people to use for his mod.(1263) if he cant accept  bugs that are on any other version, I cant really control how a mod that uses higher works with a lower version of forge, This is something I MAY look at at the end of this bugfixing release, but like people running on the modified forge servers, nothing priority, mainly because trying to swap between forge versions, or in mcpc case, different servers, causes extra hassle for edge cases

**Comment by JasonMcRay** [comment]
And isnt possible to just blacklist any GT items with Spellbinding Cloth? If not then... only thing that remains is to remove the Spellbinding cloth from game with minetweaker/modtweaker

**Comment by nekosune** [comment]
Blacklists get ... confusing to maintain especially as other mods don't use the functionality available to them to add themselves to the blacklist on load. As I said, this bug is something I will look into but not a priority as bugs that dont require me to resetup my dev env for a specific version of forge, take priority

**Comment by nekosune** [comment]
We provide an interface to let other mods say "Dont wipe enchantments off this" as part of an API. If greg is not using it, thats part of the problem

**Comment by JasonMcRay** [comment]
This issue has been solved. Closing it so it doesnt confuse people :)
