### ISSUE TITLE
[Issue maybe not a bug] ichor wands

### ISSUE THREAD

**Issue by s0meoneyoukn0w** [Thaumic-Tinkerer/ThaumicTinkerer#586]
you can make an ichorium adorned silverwood strapped silverwood scepter but not a staff

**Comment by AlfieSR** [comment]
The scepter only exists because it's a crafting handle of some sort rather than any sort of new item specifically implemented for it, a tag added to the created wand and nothing more, which is why staff-scepters can exist.

I'd be all for a ichorcloth staff partly because 1500 vis is neat, and partly because it's somewhat odd switching from all yellow-orange items to a dark purple item just because the primal staff has potency and natural regen. Also the shadowbeam consuming so much vis even without potency does provide a bit of leeway as an excuse.
