### ISSUE TITLE
Shadowbeam focus cannot receive enchantments in the Focal Manipulator.

### ISSUE THREAD

**Issue by talonos2** [Thaumic-Tinkerer/ThaumicTinkerer#786]
Tested in v2.5-471.

I'm no expert in how your code works, but it might be because you're returning an empty array in getPossibleUpgradesByRank. (Line 81) Is this intentional? If so, I'll pass word along to those complaining about it in my modpack's issue tracker.

**Comment by Zsashas** [comment]
the same thing applies to all Wand Foci added by this addon. None have any upgrades whatsoever, even basic ones.

**Comment by Wickedtemp** [comment]
I'm hoping this gets fixed relatively quickly... At the moment, shadowbeam is relatively useless against other players due to armor. My 'shock' wand focus does more damage, costs less vis, and is overall more reliable. 

The wand foci in Thaumic Tinkerer at least need a frugal/potency upgrade at each level. For shadowbeam I would recommend one upgrade that adds a chance to inflict Wither or a similar debuff onto the target. 

As for the XP drain wand focus, potency would increase the rate of charging and frugal would use less XP to charge, maybe an upgrade that adds a chance to not use XP to charge the wand. I don't know.

**Comment by shadoxxhd** [comment]
shadowbeam could have a lvl3 scatter/decay choice - either it inflicts wither, slowness and blindness, or the beam - instead of getting reflected - sorta explodes on contact with a block, scattering into ~10 short ranged new beams
if you don't take either (choose potency or frugal at lvl3) you can apply an armor piercing upgrade to the focus - doing 30% of the total damage as unblockable damage.
experience focus could have the option to drain other players xp (lvl 5 upgrade)
uprising could have a hover upgrade
telekinesis: at lvl 3 you can choose to either be able to move entities, or throw items as projectiles
recall: wormhole (creates a portal other players can follow you through) and telefrag (damage dealt at target location)
distortion: either reflects arrows back to the shooter, or is able to block ghast fireballs and wither skull projectiles
mending: heal other players around you as well, or be able to 'overheal' (absorption)
dislocation: can either move a 3x3 area at once, or move nodes (at a very high vis cost)
ender rift: either dimensionally transplaces you for a short time when opening the ender chest (so you can safely access your items) or is able to open other players ender chest (right click player)
efreets flame: plasma lance upgrade: for glassing whole planets (turns most natural blocks into glass, including 3 block ground pierce and 5x5 AoE (vis cost is greatly increased, though)
