### ISSUE TITLE
Client Kick after Level 40 Infusion

### ISSUE THREAD

**Issue by tyler2k15** [Thaumic-Tinkerer/ThaumicTinkerer#791]
Hello 

On my Hubris server, I had a player try to do a level 40 infusion. After the server restarted, the player was unable to connect with the following in console.

https://gist.githubusercontent.com/tyler2k15/712001fcf42b8ecd7bd6/raw/b437ce13f2a06090ed0a687f13736f379b97144a/ClientCrashThaumicTinkerer.txt

I was able to remove the armor from their inventory and they could then connect. After them connecting I put the armor back in their inventory but it was invisible to them so they relogged and when they logged back in the armor had vanished

**Comment by nekosune** [comment]
This crash is nothing to do with Thaumic Tinkerer, and is due to whichever mod this code is in:
at am2.armor.infusions.Dispelling.applyEffect(Dispelling.java:50) ~[Dispelling.class:?]

Which happens to be ars magica ...

Thaumic tinkerer does not appear anywhere in the stack trace, it just happens to be on the list of things that hook LivingUpdate.

**Comment by Zsashas** [comment]
It has to do with the Dispel effect specifically, it's still buggy, don't use it.
