### ISSUE TITLE
Rename Robes of the Stratosphere to Robes of the Stratocube

### ISSUE THREAD

**Issue by Cypher121** [Thaumic-Tinkerer/ThaumicTinkerer#793]
Because there are no spheres in Minecraft.

**Comment by TheCricket** [comment]
... are you serious

**Comment by Cypher121** [comment]
No, but why not?

**Comment by NolanSyKinsley** [comment]
Because although minecraft is based around cubes making every reference of a sphere be changed to a cube is a heavy handed approach.

It is named Robes of the Stratosphere because the stratosphere name gives a feeling of massive height, being on the edge of space, changing it to stratocube removes that feeling of epic height and replaces it with a sense of overused cheap in-verse joke.

**Comment by TheCricket** [comment]
^

**Comment by Cypher121** [comment]
You guys are adept at ruining jokes, aren't you?

**Comment by nekosune** [comment]
Issue tracker is a place for bugs / problems, not jokes
